-- MySQL Script generated by MySQL Workbench
-- Tue Nov 21 13:06:05 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BD_IDRUG
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BD_IDRUG
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BD_IDRUG` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema bd_idrug
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_idrug
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_idrug` DEFAULT CHARACTER SET utf8 ;
USE `BD_IDRUG` ;

-- -----------------------------------------------------
-- Table `BD_IDRUG`.`Farmacia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_IDRUG`.`Farmacia` (
  `idFarmacia` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `cnpj` VARCHAR(14) NOT NULL,
  `telefone` VARCHAR(13) NOT NULL,
  `cep` VARCHAR(6) NOT NULL,
  `logradouro` VARCHAR(60) NOT NULL,
  `estado` VARCHAR(2) NOT NULL,
  `cidade` VARCHAR(25) NOT NULL,
  `bairro` VARCHAR(25) NOT NULL,
  `status` ENUM('ATIVA', 'INATIVA') NOT NULL DEFAULT 'INATIVA',
  PRIMARY KEY (`idFarmacia`),
  UNIQUE INDEX `idFarmacia_UNIQUE` (`idFarmacia` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_IDRUG`.`CategoriaMedicamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_IDRUG`.`CategoriaMedicamento` (
  `idCategoriaMedicamento` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nomeCategoria` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idCategoriaMedicamento`),
  UNIQUE INDEX `idCategoriaMedicamento_UNIQUE` (`idCategoriaMedicamento` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_IDRUG`.`Medicamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_IDRUG`.`Medicamento` (
  `idMedicamento` INT NOT NULL AUTO_INCREMENT,
  `idCategoriaMedicamento` INT UNSIGNED NOT NULL,
  `codigoBarras` VARCHAR(20) NOT NULL,
  `nome` VARCHAR(60) NOT NULL,
  `fabricante` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`idMedicamento`),
  UNIQUE INDEX `idMedicamento_UNIQUE` (`idMedicamento` ASC) VISIBLE,
  INDEX `fk_Medicamento_CategoriaMedicamento1_idx` (`idCategoriaMedicamento` ASC) VISIBLE,
  CONSTRAINT `idCategoriaMedicamento`
    FOREIGN KEY (`idCategoriaMedicamento`)
    REFERENCES `BD_IDRUG`.`CategoriaMedicamento` (`idCategoriaMedicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_IDRUG`.`MedicamentoDisponivel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_IDRUG`.`MedicamentoDisponivel` (
  `idDisponibilizacaoMedicamento` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idMedicamento` INT NOT NULL,
  `idFarmacia` INT UNSIGNED NOT NULL,
  `dataInicioDisponibilizacao` DATETIME NOT NULL,
  `dataFimDisponibilizacao` DATETIME NOT NULL,
  `quantidadeDisponibilizacao` INT NOT NULL,
  `lote` VARCHAR(45) NOT NULL,
  `quantidade` VARCHAR(45) NOT NULL,
  `statusMedicamento` ENUM('RESERVADO', 'DISPONIVEL', 'INDISPONIVEL') NOT NULL DEFAULT 'DISPONIVEL',
  `dataVencimento` DATETIME NOT NULL,
  `quantidadeReservada` INT NOT NULL,
  `quantidadeEntregue` INT NOT NULL,
  `quantidadeDisponivel` INT NOT NULL,
  `imagem` BLOB NULL,
  PRIMARY KEY (`idDisponibilizacaoMedicamento`),
  INDEX `fk_TB_FARMACIA_has_TB_MEDICAMENTO_TB_MEDICAMENTO1_idx` (`idMedicamento` ASC) VISIBLE,
  UNIQUE INDEX `idDisponibilizacaoMedicamento_UNIQUE` (`idDisponibilizacaoMedicamento` ASC) VISIBLE,
  INDEX `fk_MedicamentoDisponivel_Farmacia1_idx` (`idFarmacia` ASC) VISIBLE,
  CONSTRAINT `idMedicamento`
    FOREIGN KEY (`idMedicamento`)
    REFERENCES `BD_IDRUG`.`Medicamento` (`idMedicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MedicamentoDisponivel_Farmacia1`
    FOREIGN KEY (`idFarmacia`)
    REFERENCES `BD_IDRUG`.`Farmacia` (`idFarmacia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_IDRUG`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_IDRUG`.`Usuario` (
  `idUsuario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idFarmacia` INT UNSIGNED NOT NULL,
  `tipoUsuario` ENUM('ADMINISTRADOR', 'FARMACEUTICO', 'SOLICITANTE') NOT NULL DEFAULT 'SOLICITANTE',
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(12) NOT NULL,
  `telefone` VARCHAR(13) NULL,
  `sexo` VARCHAR(1) NOT NULL,
  `logradouro` VARCHAR(60) NOT NULL,
  `estado` VARCHAR(2) NOT NULL,
  `cidade` VARCHAR(25) NOT NULL,
  `bairro` VARCHAR(25) NOT NULL,
  `email` VARCHAR(30) NOT NULL,
  `senha` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_TB_USUARIO_TB_FARMACIA1_idx` (`idFarmacia` ASC) INVISIBLE,
  UNIQUE INDEX `idUsuario_UNIQUE` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `idFarmacia`
    FOREIGN KEY (`idFarmacia`)
    REFERENCES `BD_IDRUG`.`Farmacia` (`idFarmacia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_IDRUG`.`SolicitacaoMedicamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_IDRUG`.`SolicitacaoMedicamento` (
  `idSolicitacaoMedicamento` INT NOT NULL AUTO_INCREMENT,
  `idDisponibilizacaoMedicamento` INT UNSIGNED NOT NULL,
  `idUsuario` INT UNSIGNED NOT NULL,
  `quantidadeSolicitada` INT NOT NULL,
  `statusSolicitacaoMedicamento` ENUM('CONCLUIDA', 'EM ANDAMENTO', 'CANCELADA') NOT NULL DEFAULT 'EM ANDAMENTO',
  `quantidadeEntregue` INT NOT NULL,
  `prazoEntrega` DATETIME NOT NULL,
  `dataSolicitacao` DATETIME NOT NULL,
  `dataEntrega` DATETIME NOT NULL,
  `cpf` VARCHAR(12) NOT NULL,
  INDEX `fk_tbDisponibilizaMedicamento_has_tbUsuario_tbUsuario1_idx` (`idUsuario` ASC) VISIBLE,
  INDEX `fk_tbDisponibilizaMedicamento_has_tbUsuario_tbDisponibiliza_idx` (`idDisponibilizacaoMedicamento` ASC) VISIBLE,
  PRIMARY KEY (`idSolicitacaoMedicamento`),
  UNIQUE INDEX `idSolicitacaoMedicamento_UNIQUE` (`idSolicitacaoMedicamento` ASC) VISIBLE,
  CONSTRAINT `idDisponibilizacaoMedicamento`
    FOREIGN KEY (`idDisponibilizacaoMedicamento`)
    REFERENCES `BD_IDRUG`.`MedicamentoDisponivel` (`idDisponibilizacaoMedicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idUsuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `BD_IDRUG`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `bd_idrug` ;

-- -----------------------------------------------------
-- Table `bd_idrug`.`__efmigrationshistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_idrug`.`__efmigrationshistory` (
  `MigrationId` VARCHAR(150) CHARACTER SET 'utf8' NOT NULL,
  `ProductVersion` VARCHAR(32) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`MigrationId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_idrug`.`aspnetroles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_idrug`.`aspnetroles` (
  `Id` VARCHAR(767) NOT NULL,
  `Name` VARCHAR(256) NULL DEFAULT NULL,
  `NormalizedName` VARCHAR(256) NULL DEFAULT NULL,
  `ConcurrencyStamp` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_idrug`.`aspnetroleclaims`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_idrug`.`aspnetroleclaims` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `RoleId` VARCHAR(767) NOT NULL,
  `ClaimType` TEXT NULL DEFAULT NULL,
  `ClaimValue` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `FK_AspNetRoleClaims_AspNetRoles_RoleId` (`RoleId` ASC) VISIBLE,
  CONSTRAINT `FK_AspNetRoleClaims_AspNetRoles_RoleId`
    FOREIGN KEY (`RoleId`)
    REFERENCES `bd_idrug`.`aspnetroles` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_idrug`.`aspnetusers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_idrug`.`aspnetusers` (
  `Id` VARCHAR(767) NOT NULL,
  `UserName` VARCHAR(256) NULL DEFAULT NULL,
  `NormalizedUserName` VARCHAR(256) NULL DEFAULT NULL,
  `Email` VARCHAR(256) NULL DEFAULT NULL,
  `NormalizedEmail` VARCHAR(256) NULL DEFAULT NULL,
  `EmailConfirmed` BIT(1) NOT NULL,
  `PasswordHash` TEXT NULL DEFAULT NULL,
  `SecurityStamp` TEXT NULL DEFAULT NULL,
  `ConcurrencyStamp` TEXT NULL DEFAULT NULL,
  `PhoneNumber` TEXT NULL DEFAULT NULL,
  `PhoneNumberConfirmed` BIT(1) NOT NULL,
  `TwoFactorEnabled` BIT(1) NOT NULL,
  `LockoutEnd` TIMESTAMP NULL DEFAULT NULL,
  `LockoutEnabled` BIT(1) NOT NULL,
  `AccessFailedCount` INT NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_idrug`.`aspnetuserclaims`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_idrug`.`aspnetuserclaims` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `UserId` VARCHAR(767) NOT NULL,
  `ClaimType` TEXT NULL DEFAULT NULL,
  `ClaimValue` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `FK_AspNetUserClaims_AspNetUsers_UserId` (`UserId` ASC) VISIBLE,
  CONSTRAINT `FK_AspNetUserClaims_AspNetUsers_UserId`
    FOREIGN KEY (`UserId`)
    REFERENCES `bd_idrug`.`aspnetusers` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_idrug`.`aspnetuserlogins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_idrug`.`aspnetuserlogins` (
  `LoginProvider` VARCHAR(128) NOT NULL,
  `ProviderKey` VARCHAR(128) NOT NULL,
  `ProviderDisplayName` TEXT NULL DEFAULT NULL,
  `UserId` VARCHAR(767) NOT NULL,
  PRIMARY KEY (`LoginProvider`, `ProviderKey`),
  INDEX `FK_AspNetUserLogins_AspNetUsers_UserId` (`UserId` ASC) VISIBLE,
  CONSTRAINT `FK_AspNetUserLogins_AspNetUsers_UserId`
    FOREIGN KEY (`UserId`)
    REFERENCES `bd_idrug`.`aspnetusers` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_idrug`.`categoriamedicamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_idrug`.`categoriamedicamento` (
  `idCategoriaMedicamento` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nomeCategoria` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idCategoriaMedicamento`),
  UNIQUE INDEX `idCategoriaMedicamento_UNIQUE` (`idCategoriaMedicamento` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_idrug`.`farmacia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_idrug`.`farmacia` (
  `idFarmacia` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `cnpj` VARCHAR(14) NOT NULL,
  `telefone` VARCHAR(13) NOT NULL,
  `cep` VARCHAR(6) NOT NULL,
  `logradouro` VARCHAR(60) NOT NULL,
  `estado` VARCHAR(2) NOT NULL,
  `cidade` VARCHAR(25) NOT NULL,
  `bairro` VARCHAR(25) NOT NULL,
  `status` ENUM('ATIVA', 'INATIVA') NOT NULL DEFAULT 'INATIVA',
  PRIMARY KEY (`idFarmacia`),
  UNIQUE INDEX `idFarmacia_UNIQUE` (`idFarmacia` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_idrug`.`medicamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_idrug`.`medicamento` (
  `idMedicamento` INT NOT NULL AUTO_INCREMENT,
  `idCategoriaMedicamento` INT UNSIGNED NOT NULL,
  `codigoBarras` VARCHAR(20) NOT NULL,
  `nome` VARCHAR(60) NOT NULL,
  `fabricante` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`idMedicamento`),
  UNIQUE INDEX `idMedicamento_UNIQUE` (`idMedicamento` ASC) VISIBLE,
  INDEX `fk_Medicamento_CategoriaMedicamento1_idx` (`idCategoriaMedicamento` ASC) VISIBLE,
  CONSTRAINT `idCategoriaMedicamento`
    FOREIGN KEY (`idCategoriaMedicamento`)
    REFERENCES `bd_idrug`.`categoriamedicamento` (`idCategoriaMedicamento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_idrug`.`medicamentodisponivel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_idrug`.`medicamentodisponivel` (
  `idDisponibilizacaoMedicamento` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idMedicamento` INT NOT NULL,
  `idFarmacia` INT UNSIGNED NOT NULL,
  `dataInicioDisponibilizacao` DATETIME NOT NULL,
  `dataFimDisponibilizacao` DATETIME NOT NULL,
  `quantidadeDisponibilizacao` INT NOT NULL,
  `lote` VARCHAR(45) NOT NULL,
  `quantidade` VARCHAR(45) NOT NULL,
  `validadeMes` VARCHAR(10) NOT NULL,
  `validadeAno` INT NOT NULL,
  `statusMedicamento` ENUM('RESERVADO', 'DISPONIVEL', 'INDISPONIVEL') NOT NULL DEFAULT 'DISPONIVEL',
  `dataVencimento` DATETIME NOT NULL,
  `quantidadeReservada` INT NOT NULL,
  `quantidadeEntregue` INT NOT NULL,
  `quantidadeDisponivel` INT NOT NULL,
  `imagem` BLOB NULL DEFAULT NULL,
  PRIMARY KEY (`idDisponibilizacaoMedicamento`),
  UNIQUE INDEX `idDisponibilizacaoMedicamento_UNIQUE` (`idDisponibilizacaoMedicamento` ASC) VISIBLE,
  INDEX `fk_TB_FARMACIA_has_TB_MEDICAMENTO_TB_MEDICAMENTO1_idx` (`idMedicamento` ASC) VISIBLE,
  INDEX `fk_MedicamentoDisponivel_Farmacia1_idx` (`idFarmacia` ASC) VISIBLE,
  CONSTRAINT `fk_MedicamentoDisponivel_Farmacia1`
    FOREIGN KEY (`idFarmacia`)
    REFERENCES `bd_idrug`.`farmacia` (`idFarmacia`),
  CONSTRAINT `idMedicamento`
    FOREIGN KEY (`idMedicamento`)
    REFERENCES `bd_idrug`.`medicamento` (`idMedicamento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_idrug`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_idrug`.`usuario` (
  `idUsuario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idFarmacia` INT UNSIGNED NOT NULL,
  `tipoUsuario` ENUM('ADMINISTRADOR', 'FARMACEUTICO', 'SOLICITANTE') NOT NULL DEFAULT 'SOLICITANTE',
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(12) NOT NULL,
  `telefone` VARCHAR(13) NULL DEFAULT NULL,
  `sexo` VARCHAR(1) NOT NULL,
  `logradouro` VARCHAR(60) NOT NULL,
  `estado` VARCHAR(2) NOT NULL,
  `cidade` VARCHAR(25) NOT NULL,
  `bairro` VARCHAR(25) NOT NULL,
  `email` VARCHAR(30) NOT NULL,
  `senha` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `idUsuario_UNIQUE` (`idUsuario` ASC) VISIBLE,
  INDEX `fk_TB_USUARIO_TB_FARMACIA1_idx` (`idFarmacia` ASC) INVISIBLE,
  CONSTRAINT `idFarmacia`
    FOREIGN KEY (`idFarmacia`)
    REFERENCES `bd_idrug`.`farmacia` (`idFarmacia`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_idrug`.`solicitacaomedicamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_idrug`.`solicitacaomedicamento` (
  `idSolicitacaoMedicamento` INT NOT NULL AUTO_INCREMENT,
  `idDisponibilizacaoMedicamento` INT UNSIGNED NOT NULL,
  `idUsuario` INT UNSIGNED NOT NULL,
  `quantidadeSolicitada` INT NOT NULL,
  `statusSolicitacaoMedicamento` ENUM('CONCLUIDA', 'EM ANDAMENTO', 'CANCELADA') NOT NULL DEFAULT 'EM ANDAMENTO',
  `quantidadeEntregue` INT NOT NULL,
  `prazoEntrega` DATETIME NOT NULL,
  `dataSolicitacao` DATETIME NOT NULL,
  `dataEntrega` DATETIME NOT NULL,
  `cpf` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`idSolicitacaoMedicamento`),
  UNIQUE INDEX `idSolicitacaoMedicamento_UNIQUE` (`idSolicitacaoMedicamento` ASC) VISIBLE,
  INDEX `fk_tbDisponibilizaMedicamento_has_tbUsuario_tbUsuario1_idx` (`idUsuario` ASC) VISIBLE,
  INDEX `fk_tbDisponibilizaMedicamento_has_tbUsuario_tbDisponibiliza_idx` (`idDisponibilizacaoMedicamento` ASC) VISIBLE,
  CONSTRAINT `idDisponibilizacaoMedicamento`
    FOREIGN KEY (`idDisponibilizacaoMedicamento`)
    REFERENCES `bd_idrug`.`medicamentodisponivel` (`idDisponibilizacaoMedicamento`),
  CONSTRAINT `idUsuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `bd_idrug`.`usuario` (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
